spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/testeDelegate

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    database:
      type: h2
      schema-update: true